const STATION_NAMES = {
    "22ND STREET LIGHT RAIL STATION": { es: "Estación de Tren Ligero Calle 22", zh: "第22街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ 22-Я СТРИТ", bn: "২২ তম স্ট্রিট লাইট রেল স্টেশন" },
    "2ND STREET LIGHT RAIL STATION": { es: "Estación de Tren Ligero Calle 2", zh: "第2街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ 2-Я СТРИТ", bn: "২য় স্ট্রিট লাইট রেল স্টেশন" },
    "30TH ST. PHL.": { es: "Calle 30 - Filadelfia", zh: "第30街·费城", ru: "30-Я СТРИТ — ФИЛАДЕЛЬФИЯ", bn: "৩০তম স্ট্রিট ফিলাডেলফিয়া" },
    "34TH STREET LIGHT RAIL STATION": { es: "Estación de Tren Ligero Calle 34", zh: "第34街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ 34-Я СТРИТ", bn: "৩৪তম স্ট্রিট লাইট রেল স্টেশন" },
    "36TH STREET LIGHT RAIL STATION": { es: "Estación de Tren Ligero Calle 36", zh: "第36街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ 36-Я СТРИТ", bn: "৩৬তম স্ট্রিট লাইট রেল স্টেশন" },
    "45TH STREET LIGHT RAIL STATION": { es: "Estación de Tren Ligero Calle 45", zh: "第45街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ 45-Я СТРИТ", bn: "৪৫তম স্ট্রিট লাইট রেল স্টেশন" },
    "8TH STREET LIGHT RAIL STATION": { es: "Estación de Tren Ligero Calle 8", zh: "第8街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ 8-Я СТРИТ", bn: "৮ম স্ট্রিট লাইট রেল স্টেশন" },
    "9TH STREET LIGHT RAIL STATION": { es: "Estación de Tren Ligero Calle 9", zh: "第9街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ 9-Я СТРИТ", bn: "৯ম স্ট্রিট লাইট রেল স্টেশন" },
    "ABERDEEN-MATAWAN": { es: "Aberdeen-Matawan", zh: "阿伯丁-马塔万", ru: "АБЕРДИН-МАТАУАН", bn: "অ্যাবারডিন-মাতাওয়ান" },
    "ABSECON": { es: "Absécon", zh: "阿布西肯", ru: "АБСЕКОН", bn: "অ্যাবসেকন" },
    "ALLENDALE": { es: "Allendale", zh: "艾伦代尔", ru: "АЛЛЕНДЕЙЛ", bn: "অ্যালেনডেল" },
    "ALLENHURST": { es: "Allenhurst", zh: "阿伦赫斯特", ru: "АЛЛЕНХЕРСТ", bn: "অ্যালেনহার্স্ট" },
    "ANDERSON STREET": { es: "Calle Anderson", zh: "安德森街", ru: "АНДЕРСОН-СТРИТ", bn: "অ্যান্ডারসন স্ট্রিট" },
    "ANNANDALE": { es: "Annandale", zh: "安南代尔", ru: "АННАНДЕЙЛ", bn: "অ্যানানডেল" },
    "AQUARIUM LIGHT RAIL STATION": { es: "Estación de Tren Ligero Acuario", zh: "水族馆轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ АКВАРИУМ", bn: "অ্যাকোয়ারিয়াম লাইট রেল স্টেশন" },
    "ASBURY PARK": { es: "Asbury Park", zh: "阿斯伯里帕克", ru: "АСБЕРИ-ПАРК", bn: "অ্যাসবেরি পার্ক" },
    "ATCO": { es: "Atco", zh: "阿特科", ru: "АТКО", bn: "অ্যাটকো" },
    "ATLANTIC CITY": { es: "Ciudad Atlántica", zh: "大西洋城", ru: "АТЛАНТИК-СИТИ", bn: "আটলান্টিক সিটি" },
    "ATLANTIC STREET LIGHT RAIL STATION": { es: "Estación de Tren Ligero Calle Atlántico", zh: "大西洋街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ АТЛАНТИК-СТРИТ", bn: "আটলান্টিক স্ট্রিট লাইট রেল স্টেশন" },
    "AVENEL": { es: "Avenel", zh: "阿维内尔", ru: "АВЕНЕЛ", bn: "অ্যাভেনেল" },
    "BASKING RIDGE": { es: "Basking Ridge", zh: "巴斯金岭", ru: "БАСКИНГ-РИДЖ", bn: "বাস্কিং রিজ" },
    "BAY HEAD": { es: "Bahía Cabo", zh: "贝黑德", ru: "БЕЙ-ХЕД", bn: "বে হেড" },
    "BAY STREET": { es: "Calle Bahía", zh: "贝街", ru: "БЕЙ-СТРИТ", bn: "বে স্ট্রিট" },
    "BELMAR": { es: "Belmar", zh: "贝尔马", ru: "БЕЛМАР", bn: "বেলমার" },
    "BERGENLINE AVE": { es: "Av. Bergenline", zh: "卑尔根莱茵大道", ru: "БЕРГЕНЛАЙН-АВЕ", bn: "বার্গেনলাইন অ্যাভে" },
    "BERKELEY HEIGHTS": { es: "Berkeley Heights", zh: "伯克利高地", ru: "БЕРКЛИ-ХАЙТС", bn: "বার্কলে হাইটস" },
    "BERNARDSVILLE": { es: "Bernardsville", zh: "伯纳德维尔", ru: "БЕРНАРДСВИЛЛ", bn: "বার্নার্ডসভিল" },
    "BEVERLY/EDGEWATER PARK LIGHT RAIL STA": { es: "Estación Tren Ligero Beverly/Edgewater Park", zh: "贝弗利/埃奇沃特公园轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ БЕВЕРЛИ/ЭДЖУОТЕР-ПАРК", bn: "বেভারলি/এজওয়াটার পার্ক লাইট রেল স্টেশন" },
    "BLOOMFIELD": { es: "Bloomfield", zh: "布鲁姆菲尔德", ru: "БЛУМФИЛД", bn: "ব্লুমফিল্ড" },
    "BLOOMFIELD AVENUE LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. Bloomfield", zh: "布鲁姆菲尔德大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ БЛУМФИЛД-АВЕНЮ", bn: "ব্লুমফিল্ড অ্যাভিনিউ লাইট রেল স্টেশন" },
    "BOONTON": { es: "Boonton", zh: "布恩顿", ru: "БУНТОН", bn: "বুনটন" },
    "BORDENTOWN LIGHT RAIL STATION": { es: "Estación Tren Ligero Bordentown", zh: "博登镇轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ БОРДЕНТАУН", bn: "বর্ডেনটাউন লাইট রেল স্টেশন" },
    "BOUND BROOK": { es: "Bound Brook", zh: "邦德布鲁克", ru: "БАУНД-БРУК", bn: "বাউন্ড ব্রুক" },
    "BRADLEY BEACH": { es: "Playa Bradley", zh: "布拉德利海滩", ru: "БРАДЛИ-БИЧ", bn: "ব্র্যাডলি বিচ" },
    "BRANCH BROOK PARK LIGHT RAIL STATION": { es: "Estación Tren Ligero Parque Branch Brook", zh: "布兰奇布鲁克公园轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ БРАНЧ-БРУК-ПАРК", bn: "ব্রাঞ্চ ব্রুক পার্ক লাইট রেল স্টেশন" },
    "BRICK CHURCH": { es: "Iglesia Brick", zh: "布里克教堂", ru: "БРИК-ЧЁРЧ", bn: "ব্রিক চার্চ" },
    "BRIDGEWATER": { es: "Bridgewater", zh: "布里奇沃特", ru: "БРИДЖВОТЕР", bn: "ব্রিজওয়াটার" },
    "BROAD STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Broad", zh: "布罗德街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ БРОД-СТРИТ", bn: "ব্রড স্ট্রিট লাইট রেল স্টেশন" },
    "BROADWAY": { es: "Broadway", zh: "百老汇", ru: "БРОДВЕЙ", bn: "ব্রডওয়ে" },
    "BURLINGTON SOUTH LIGHT RAIL STATION": { es: "Estación Tren Ligero Burlington Sur", zh: "南伯灵顿轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ БЕРЛИНГТОН-САУТ", bn: "বার্লিংটন সাউথ লাইট রেল স্টেশন" },
    "BURLINGTON TOWNE CTR LIGHT RAIL STATION": { es: "Estación Tren Ligero Centro Burlington Towne", zh: "伯灵顿市中心轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ЦЕНТР БЕРЛИНГТОН-ТАУН", bn: "বার্লিংটন টাউন সেন্টার লাইট রেল স্টেশন" },
    "CAMPBELL HALL": { es: "Campbell Hall", zh: "坎贝尔厅", ru: "КЭМБЕЛЛ-ХОЛЛ", bn: "ক্যাম্পবেল হল" },
    "CASS STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Cass", zh: "卡斯街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ КАСС-СТРИТ", bn: "ক্যাস স্ট্রিট লাইট রেল স্টেশন" },
    "CHATHAM": { es: "Chatham", zh: "查塔姆", ru: "ЧАТЕМ", bn: "চ্যাথাম" },
    "CHERRY HILL": { es: "Colina Cherry", zh: "樱桃山", ru: "ЧЕРРИ-ХИЛЛ", bn: "চেরি হিল" },
    "CINNAMINSON LIGHT RAIL STATION": { es: "Estación Tren Ligero Cinnaminson", zh: "辛纳明森轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ СИННАМИНСОН", bn: "সিনামিনসন লাইট রেল স্টেশন" },
    "CLIFTON": { es: "Clifton", zh: "克利夫顿", ru: "КЛИФТОН", bn: "ক্লিফটন" },
    "COMMUNIPAW JUNCTION": { es: "Empalme Communipaw", zh: "科穆尼波枢纽", ru: "КОММУНИПО-ДЖАНКШН", bn: "কমিউনিপাও জংশন" },
    "CONVENT": { es: "Convento", zh: "修道院", ru: "КОНВЕНТ", bn: "কনভেন্ট" },
    "COOPER STREET/RUTGERS LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Cooper/Rutgers", zh: "库珀街/罗格斯轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ КУПЕР-СТРИТ/РАТГЕРС", bn: "কুপার স্ট্রিট/রাটগার্স লাইট রেল স্টেশন" },
    "CRANFORD": { es: "Cranford", zh: "克兰福德", ru: "КРАНФОРД", bn: "ক্র্যানফোর্ড" },
    "DANFORTH AVENUE LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. Danforth", zh: "丹福斯大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ДАНФОРТ-АВЕНЮ", bn: "ড্যানফোর্থ অ্যাভিনিউ লাইট রেল স্টেশন" },
    "DAVENPORT AVENUE LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. Davenport", zh: "达文波特大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ДЭВЕНПОРТ-АВЕНЮ", bn: "ডেভেনপোর্ট অ্যাভিনিউ লাইট রেল স্টেশন" },
    "DELANCO LIGHT RAIL STATION": { es: "Estación Tren Ligero Delanco", zh: "德兰科轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ДЕЛАНКО", bn: "ডেলানকো লাইট রেল স্টেশন" },
    "DELAWANNA": { es: "Delawanna", zh: "德拉瓦纳", ru: "ДЕЛАВАННА", bn: "ডেলাওয়ানা" },
    "DENVILLE": { es: "Denville", zh: "登维尔", ru: "ДЕНВИЛЛ", bn: "ডেনভিল" },
    "DOVER": { es: "Dover", zh: "多佛", ru: "ДОВЕР", bn: "ডোভার" },
    "DUNELLEN": { es: "Dunellen", zh: "杜内伦", ru: "ДАНЕЛЛЕН", bn: "ডুনেলেন" },
    "EAST ORANGE": { es: "Orange Este", zh: "东奥兰治", ru: "ИСТ-ОРАНДЖ", bn: "ইস্ট অরেঞ্জ" },
    "EDISON STATION": { es: "Estación Edison", zh: "爱迪生站", ru: "СТАНЦИЯ ЭДИСОН", bn: "এডিসন স্টেশন" },
    "EGG HARBOR": { es: "Puerto Egg", zh: "蛋港", ru: "ЭГГ-ХАРБОР", bn: "এগ হারবার" },
    "ELBERON": { es: "Elberon", zh: "埃尔伯隆", ru: "ЭЛБЕРОН", bn: "এলবেরন" },
    "ELIZABETH": { es: "Elizabeth", zh: "伊丽莎白", ru: "ЭЛИЗАБЕТ", bn: "এলিজাবেথ" },
    "EMERSON": { es: "Emerson", zh: "埃默森", ru: "ЭМЕРСОН", bn: "এমারসন" },
    "ENTERTAINMENT CENTER LIGHT RAIL STATION": { es: "Estación Tren Ligero Centro de Entretenimiento", zh: "娱乐中心轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ЦЕНТР РАЗВЛЕЧЕНИЙ", bn: "এন্টারটেইনমেন্ট সেন্টার লাইট রেল স্টেশন" },
    "ESSEX STREET": { es: "Calle Essex", zh: "埃塞克斯街", ru: "ЭССЕКС-СТРИТ", bn: "এসেক্স স্ট্রিট" },
    "ESSEX STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Essex", zh: "埃塞克斯街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ЭССЕКС-СТРИТ", bn: "এসেক্স স্ট্রিট লাইট রেল স্টেশন" },
    "EXCHANGE PLACE LIGHT RAIL STATION": { es: "Estación Tren Ligero Lugar de Cambio", zh: "交易广场轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ЭКСЧЕЙНДЖ-ПЛЕЙС", bn: "এক্সচেঞ্জ প্লেস লাইট রেল স্টেশন" },
    "FANWOOD": { es: "Fanwood", zh: "范伍德", ru: "ФАНВУД", bn: "ফ্যানউড" },
    "FAR HILLS": { es: "Colinas Lejanas", zh: "远山", ru: "ФАР-ХИЛЛС", bn: "ফার হিলস" },
    "FLORENCE LIGHT RAIL STATION": { es: "Estación Tren Ligero Florencia", zh: "佛罗伦萨轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ФЛОРЕНС", bn: "ফ্লোরেন্স লাইট রেল স্টেশন" },
    "GARFIELD": { es: "Garfield", zh: "加菲尔德", ru: "ГАРФИЛД", bn: "গারফিল্ড" },
    "GARFIELD AVENUE LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. Garfield", zh: "加菲尔德大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ГАРФИЛД-АВЕНЮ", bn: "গারফিল্ড অ্যাভিনিউ লাইট রেল স্টেশন" },
    "GARWOOD": { es: "Garwood", zh: "加伍德", ru: "ГАРВУД", bn: "গারউড" },
    "GILLETTE": { es: "Gillette", zh: "吉列", ru: "ЖИЛЕТТ", bn: "জিলেট" },
    "GLADSTONE": { es: "Gladstone", zh: "格拉德斯通", ru: "ГЛАДСТОУН", bn: "গ্ল্যাডস্টোন" },
    "GLEN RIDGE": { es: "Glen Ridge", zh: "格伦岭", ru: "ГЛЕН-РИДЖ", bn: "গ্লেন রিজ" },
    "GLEN ROCK BORO HALL": { es: "Salón Municipal Glen Rock", zh: "格伦罗克市政厅", ru: "МЭРИЯ ГЛЕН-РОК", bn: "গ্লেন রক বরো হল" },
    "GLEN ROCK MAIN LINE": { es: "Línea Principal Glen Rock", zh: "格伦罗克主线", ru: "ГЛЕН-РОК МЕЙН-ЛАЙН", bn: "গ্লেন রক মেইন লাইন" },
    "GROVE STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Grove", zh: "格罗夫街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ГРОВ-СТРИТ", bn: "গ্রোভ স্ট্রিট লাইট রেল স্টেশন" },
    "HACKETTSTOWN": { es: "Hackettstown", zh: "哈克特斯敦", ru: "ХАКЕТТСТАУН", bn: "হ্যাকেটস্টাউন" },
    "HAMILTON": { es: "Hamilton", zh: "汉密尔顿", ru: "ГАМИЛЬТОН", bn: "হ্যামিলটন" },
    "HAMILTON AVENUE LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. Hamilton", zh: "汉密尔顿大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ГАМИЛЬТОН-АВЕНЮ", bn: "হ্যামিলটন অ্যাভিনিউ লাইট রেল স্টেশন" },
    "HAMMONTON": { es: "Hammonton", zh: "哈蒙顿", ru: "ХАММОНТОН", bn: "হ্যামনটন" },
    "HARBORSIDE LIGHT RAIL STATION": { es: "Estación Tren Ligero Harborside", zh: "港湾畔轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ХАРБОРСАЙД", bn: "হার্বরসাইড লাইট রেল স্টেশন" },
    "HARRIET TUBMAN SQUARE LIGHT RAIL STATION": { es: "Estación Tren Ligero Plaza Harriet Tubman", zh: "哈丽特·塔布曼广场轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ПЛОЩАДЬ ХАРРИЕТ ТАБМЕН", bn: "হ্যারিয়েট টাবম্যান স্কয়ার লাইট রেল স্টেশন" },
    "HARRIMAN": { es: "Harriman", zh: "哈里曼", ru: "ХАРРИМАН", bn: "হ্যারিম্যান" },
    "HARSIMUS COVE LIGHT RAIL STATION": { es: "Estación Tren Ligero Ensenada Harsimus", zh: "哈西姆斯湾轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ХАРСИМУС-КОУВ", bn: "হারসিমাস কোভ লাইট রেল স্টেশন" },
    "HAWTHORNE": { es: "Hawthorne", zh: "霍桑", ru: "ХОТОРН", bn: "হথর্ন" },
    "HAZLET": { es: "Hazlet", zh: "哈兹莱特", ru: "ХАЗЛЕТ", bn: "হাজলেট" },
    "HIGH BRIDGE": { es: "Puente Alto", zh: "高桥", ru: "ХАЙ-БРИДЖ", bn: "হাই ব্রিজ" },
    "HIGHLAND AVENUE": { es: "Av. Highland", zh: "高地大道", ru: "ХАЙЛЕНД-АВЕНЮ", bn: "হাইল্যান্ড অ্যাভিনিউ" },
    "HILLSDALE": { es: "Hillsdale", zh: "希尔斯代尔", ru: "ХИЛЛСДЕЙЛ", bn: "হিলসডেল" },
    "HOBOKEN": { es: "Hoboken", zh: "霍博肯", ru: "ХОБОКЕН", bn: "হবোকেন" },
    "HOBOKEN TERMINAL LIGHT RAIL STATION": { es: "Estación Tren Ligero Terminal Hoboken", zh: "霍博肯总站轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ТЕРМИНАЛ ХОБОКЕН", bn: "হবোকেন টার্মিনাল লাইট রেল স্টেশন" },
    "HOHOKUS": { es: "Hohokus", zh: "霍霍库斯", ru: "ХОХОКУС", bn: "হোহোকাস" },
    "JERSEY AVE.": { es: "Av. Jersey", zh: "泽西大道", ru: "ДЖЕРСИ-АВЕ", bn: "জার্সি অ্যাভে" },
    "JERSEY AVENUE LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. Jersey", zh: "泽西大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ДЖЕРСИ-АВЕНЮ", bn: "জার্সি অ্যাভিনিউ লাইট রেল স্টেশন" },
    "LAKE HOPATCONG": { es: "Lago Hopatcong", zh: "霍帕特孔湖", ru: "ОЗЕРО ХОПАТКОНГ", bn: "লেক হোপাটকং" },
    "LEBANON": { es: "Líbano", zh: "黎巴嫩", ru: "ЛИВАН", bn: "লেবানন" },
    "LIBERTY STATE PARK-RIDE LIGHT RAIL STA": { es: "Estación Tren Ligero Parque Estatal Liberty", zh: "自由州立公园轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ЛИБЕРТИ-СТЕЙТ-ПАРК", bn: "লিবার্টি স্টেট পার্ক-রাইড লাইট রেল স্টেশন" },
    "LINCOLN HARBOR LIGHT RAIL STATION": { es: "Estación Tren Ligero Puerto Lincoln", zh: "林肯港轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ЛИНКОЛЬН-ХАРБОР", bn: "লিংকন হারবার লাইট রেল স্টেশন" },
    "LINCOLN PARK": { es: "Parque Lincoln", zh: "林肯公园", ru: "ЛИНКОЛЬН-ПАРК", bn: "লিংকন পার্ক" },
    "LINDEN": { es: "Linden", zh: "林登", ru: "ЛИНДЕН", bn: "লিন্ডেন" },
    "LINDENWOLD": { es: "Lindenwold", zh: "林登沃尔德", ru: "ЛИНДЕНВОЛД", bn: "লিন্ডেনওল্ড" },
    "LITTLE FALLS": { es: "Cascadas Pequeñas", zh: "小瀑布", ru: "ЛИТТЛ-ФОЛС", bn: "লিটল ফলস" },
    "LITTLE SILVER": { es: "Plata Pequeña", zh: "小银", ru: "ЛИТТЛ-СИЛВЕР", bn: "লিটল সিলভার" },
    "LONG BRANCH": { es: "Rama Larga", zh: "长支线", ru: "ЛОНГ-БРАНЧ", bn: "লং ব্রাঞ্চ" },
    "LYNDHURST": { es: "Lyndhurst", zh: "林德赫斯特", ru: "ЛИНДХЕРСТ", bn: "লিন্ডহার্স্ট" },
    "LYONS": { es: "Lyons", zh: "莱昂斯", ru: "ЛАЙОНС", bn: "লিয়ন্স" },
    "MADISON": { es: "Madison", zh: "麦迪逊", ru: "МЭДИСОН", bn: "ম্যাডিসন" },
    "MAHWAH": { es: "Mahwah", zh: "马瓦", ru: "МАУА", bn: "মাহওয়াহ" },
    "MANASQUAN": { es: "Manasquan", zh: "马纳斯宽", ru: "МАНАСКУАН", bn: "মানাসকুয়ান" },
    "MAPLEWOOD": { es: "Madera de Arce", zh: "枫木", ru: "МЕЙПЛВУД", bn: "ম্যাপলউড" },
    "MARIN BOULEVARD LIGHT RAIL STATION": { es: "Estación Tren Ligero Bulevar Marin", zh: "马林大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ МАРИН-БУЛЬВАР", bn: "মারিন বুলেভার্ড লাইট রেল স্টেশন" },
    "MEADOWLANDS RAIL STATION": { es: "Estación de Ferrocarril Meadowlands", zh: "梅多兰兹火车站", ru: "Ж/Д СТАНЦИЯ МЕДОУЛЕНДС", bn: "মেডোল্যান্ডস রেল স্টেশন" },
    "METROPARK": { es: "Metropark", zh: "都会公园", ru: "МЕТРОПАРК", bn: "মেট্রোপার্ক" },
    "METUCHEN": { es: "Metuchen", zh: "梅图琴", ru: "МЕТУЧЕН", bn: "মেটুচেন" },
    "MIDDLETOWN NJ": { es: "Middletown NJ", zh: "米德尔敦（新泽西）", ru: "МИДДЛТАУН (НЬЮ-ДЖЕРСИ)", bn: "মিডলটাউন এনজে" },
    "MIDDLETOWN NY": { es: "Middletown NY", zh: "米德尔敦（纽约）", ru: "МИДДЛТАУН (НЬЮ-ЙОРК)", bn: "মিডলটাউন এনওয়াই" },
    "MILITARY PARK LIGHT RAIL STATION": { es: "Estación Tren Ligero Parque Militar", zh: "军事公园轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ МИЛИТАРИ-ПАРК", bn: "মিলিটারি পার্ক লাইট রেল স্টেশন" },
    "MILLBURN": { es: "Millburn", zh: "米尔本", ru: "МИЛЛБЕРН", bn: "মিলবার্ন" },
    "MILLINGTON": { es: "Millington", zh: "米林顿", ru: "МИЛЛИНГТОН", bn: "মিলিংটন" },
    "MLK DRIVE LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. MLK", zh: "马丁·路德·金大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ МЛК-ДРАЙВ", bn: "এমএলকে ড্রাইভ লাইট রেল স্টেশন" },
    "MONMOUTH PARK": { es: "Parque Monmouth", zh: "蒙茅斯公园", ru: "МОНМАУТ-ПАРК", bn: "মনমাউথ পার্ক" },
    "MONTCLAIR HEIGHTS": { es: "Alturas de Montclair", zh: "蒙克莱尔高地", ru: "МОНТКЛЕР-ХАЙТС", bn: "মন্টক্লেয়ার হাইটস" },
    "MONTVALE": { es: "Montvale", zh: "蒙特维尔", ru: "МОНТВЕЙЛ", bn: "মন্টভেল" },
    "MORRIS PLAINS": { es: "Llanos Morris", zh: "莫里斯平原", ru: "МОРРИС-ПЛЕЙНС", bn: "মরিস প্লেইনস" },
    "MORRISTOWN": { es: "Morristown", zh: "莫里斯敦", ru: "МОРРИСТАУН", bn: "মরিস্টাউন" },
    "MOUNT ARLINGTON": { es: "Monte Arlington", zh: "阿灵顿山", ru: "МАУНТ-АРЛИНГТОН", bn: "মাউন্ট আর্লিংটন" },
    "MOUNT OLIVE": { es: "Monte Oliva", zh: "奥利夫山", ru: "МАУНТ-ОЛИВ", bn: "মাউন্ট অলিভ" },
    "MOUNT TABOR": { es: "Monte Tabor", zh: "塔博尔山", ru: "МАУНТ-ТЕЙБОР", bn: "মাউন্ট ট্যাবর" },
    "MOUNTAIN AVENUE": { es: "Av. Montaña", zh: "山大道", ru: "МАУНТИН-АВЕНЮ", bn: "মাউন্টেন অ্যাভিনিউ" },
    "MOUNTAIN LAKES": { es: "Lagos de Montaña", zh: "山湖", ru: "МАУНТИН-ЛЕЙКС", bn: "মাউন্টেন লেকস" },
    "MOUNTAIN STATION": { es: "Estación Montaña", zh: "山站", ru: "СТАНЦИЯ МАУНТИН", bn: "মাউন্টেন স্টেশন" },
    "MOUNTAIN VIEW": { es: "Vista de Montaña", zh: "山景", ru: "МАУНТИН-ВЬЮ", bn: "মাউন্টেন ভিউ" },
    "MSU": { es: "Universidad Estatal Montclair", zh: "蒙特克莱州立大学", ru: "УНИВЕРСИТЕТ МОНТКЛЕР", bn: "এমএসইউ" },
    "MURRAY HILL": { es: "Colina Murray", zh: "默里山", ru: "МЮРРЕЙ-ХИЛЛ", bn: "মারে হিল" },
    "NANUET": { es: "Nanuet", zh: "纳努埃特", ru: "НАНУЭТ", bn: "নানুয়েট" },
    "NETCONG": { es: "Netcong", zh: "内特孔", ru: "НЕТКОНГ", bn: "নেটকং" },
    "NETHERWOOD": { es: "Netherwood", zh: "内瑟伍德", ru: "НЕТЕРВУД", bn: "নেদারউড" },
    "NEW BRIDGE LANDING": { es: "Embarcadero New Bridge", zh: "新桥码头", ru: "НЬЮ-БРИДЖ-ЛЕНДИНГ", bn: "নিউ ব্রিজ ল্যান্ডিং" },
    "NEW BRUNSWICK": { es: "Nueva Brunswick", zh: "新不伦瑞克", ru: "НЬЮ-БРАНСУИК", bn: "নিউ ব্রান্সউইক" },
    "NEW PROVIDENCE": { es: "Nueva Providencia", zh: "新普罗维登斯", ru: "НЬЮ-ПРОВИДЕНС", bn: "নিউ প্রভিডেন্স" },
    "NEW YORK PENN STATION": { es: "Estación Penn Nueva York", zh: "纽约宾夕法尼亚车站", ru: "НЬЮ-ЙОРК ПЕНН СТЕЙШН", bn: "নিউ ইয়র্ক পেন স্টেশন" },
    "NEWARK AIRPORT RAILROAD STATION": { es: "Estación de Tren Aeropuerto Newark", zh: "纽瓦克机场火车站", ru: "Ж/Д СТАНЦИЯ АЭРОПОРТ НЬЮАРКА", bn: "নেওয়ার্ক বিমানবন্দর রেল স্টেশন" },
    "NEWARK BROAD ST": { es: "Calle Broad Newark", zh: "纽瓦克布罗德街", ru: "НЬЮАРК-БРОД-СТРИТ", bn: "নেওয়ার্ক ব্রড স্ট্রিট" },
    "NEWARK PENN STATION": { es: "Estación Penn Newark", zh: "纽瓦克宾夕法尼亚车站", ru: "НЬЮАРК ПЕНН СТЕЙШН", bn: "নেওয়ার্ক পেন স্টেশন" },
    "NEWPORT LIGHT RAIL STATION": { es: "Estación Tren Ligero Newport", zh: "纽波特轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ НЬЮПОРТ", bn: "নিউপোর্ট লাইট রেল স্টেশন" },
    "NJPAC/CENTRE STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero NJPAC/Calle Centre", zh: "NJPAC/中心街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ НДЖПАК/СЕНТР-СТРИТ", bn: "এনজেপিএসি/সেন্টার স্ট্রিট লাইট রেল স্টেশন" },
    "NORFOLK STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Norfolk", zh: "诺福克街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ НОРФОЛК-СТРИТ", bn: "নরফোক স্ট্রিট লাইট রেল স্টেশন" },
    "NORTH BRANCH": { es: "Rama Norte", zh: "北支线", ru: "НОРТ-БРАНЧ", bn: "নর্থ ব্রাঞ্চ" },
    "NORTH ELIZABETH": { es: "Elizabeth Norte", zh: "北伊丽莎白", ru: "НОРТ-ЭЛИЗАБЕТ", bn: "নর্থ এলিজাবেথ" },
    "ORADELL": { es: "Oradell", zh: "奥拉德尔", ru: "ОРАДЕЛЛ", bn: "ওরাডেল" },
    "ORANGE": { es: "Orange", zh: "奥兰治", ru: "ОРАНДЖ", bn: "অরেঞ্জ" },
    "ORANGE STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Orange", zh: "奥兰治街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ОРАНДЖ-СТРИТ", bn: "অরেঞ্জ স্ট্রিট লাইট রেল স্টেশন" },
    "OTISVILLE": { es: "Otisville", zh: "奥蒂斯维尔", ru: "ОТИСВИЛЛ", bn: "ওটিসভিল" },
    "PALMYRA LIGHT RAIL STATION": { es: "Estación Tren Ligero Palmira", zh: "帕尔米拉轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ПАЛМАЙРА", bn: "পালমিরা লাইট রেল স্টেশন" },
    "PARK AVENUE NEWARK LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. Park Newark", zh: "纽瓦克公园大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ПАРК-АВЕНЮ НЬЮАРК", bn: "পার্ক অ্যাভিনিউ নেওয়ার্ক লাইট রেল স্টেশন" },
    "PARK RIDGE": { es: "Cresta del Parque", zh: "帕克里奇", ru: "ПАРК-РИДЖ", bn: "পার্ক রিজ" },
    "PASSAIC": { es: "Passaic", zh: "帕塞伊克", ru: "ПАССЕЙК", bn: "প্যাসাইক" },
    "PATERSON": { es: "Paterson", zh: "帕特森", ru: "ПАТЕРСОН", bn: "প্যাটারসন" },
    "PEAPACK": { es: "Peapack", zh: "皮帕克", ru: "ПИПАК", bn: "পিপ্যাক" },
    "PEARL RIVER": { es: "Río Perla", zh: "珍珠河", ru: "ПЁРЛ-РИВЕР", bn: "পার্ল রিভার" },
    "PENN STATION LIGHT RAIL ARRIVAL": { es: "Llegada Tren Ligero Estación Penn", zh: "宾州车站轻轨到达", ru: "ПРИБЫТИЕ ЛАЙТ-РЕЙЛ ПЕНН-СТЕЙШН", bn: "পেন স্টেশন লাইট রেল আগমন" },
    "PENN STATION LIGHT RAIL DEPARTURE": { es: "Salida Tren Ligero Estación Penn", zh: "宾州车站轻轨出发", ru: "ОТПРАВЛЕНИЕ ЛАЙТ-РЕЙЛ ПЕНН-СТЕЙШН", bn: "পেন স্টেশন লাইট রেল প্রস্থান" },
    "PENNSAUKEN TRANSIT CENTER": { es: "Centro de Tránsito Pennsauken", zh: "彭索肯交通中心", ru: "ТРАНЗИТНЫЙ ЦЕНТР ПЕННСОКЕН", bn: "পেনসাউকেন ট্রানজিট সেন্টার" },
    "PENNSAUKEN TRANSIT CENTER LIGHT RAIL STA": { es: "Estación Tren Ligero Centro de Tránsito Pennsauken", zh: "彭索肯交通中心轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ТРАНЗИТНЫЙ ЦЕНТР ПЕННСОКЕН", bn: "পেনসাউকেন ট্রানজিট সেন্টার লাইট রেল স্টেশন" },
    "PERTH AMBOY": { es: "Perth Amboy", zh: "珀斯安博伊", ru: "ПЕРТ-АМБОЙ", bn: "পার্থ অ্যামবয়" },
    "PLAINFIELD": { es: "Plainfield", zh: "普莱恩菲尔德", ru: "ПЛЕЙНФИЛД", bn: "প্লেইনফিল্ড" },
    "PLAUDERVILLE": { es: "Plauderville", zh: "普劳德维尔", ru: "ПЛАУДЕРВИЛЛ", bn: "প্লাউডারভিল" },
    "POINT PLEASANT": { es: "Punta Pleasant", zh: "欢乐点", ru: "ПОЙНТ-ПЛЕЗАНТ", bn: "পয়েন্ট প্লিজ্যান্ট" },
    "PORT IMPERIAL HBLR STATION": { es: "Estación HBLR Puerto Imperial", zh: "帝国港HBLR站", ru: "СТАНЦИЯ ХБЛР ПОРТ-ИМПЕРИАЛ", bn: "পোর্ট ইম্পেরিয়াল এইচবিএলআর স্টেশন" },
    "PORT JERVIS": { es: "Puerto Jervis", zh: "杰维斯港", ru: "ПОРТ-ДЖЕРВИС", bn: "পোর্ট জার্ভিস" },
    "PRINCETON": { es: "Princeton", zh: "普林斯顿", ru: "ПРИНСТОН", bn: "প্রিন্সটন" },
    "PRINCETON JCT.": { es: "Empalme Princeton", zh: "普林斯顿枢纽", ru: "ПРИНСТОН-ДЖАНКШН", bn: "প্রিন্সটন জংশন" },
    "RADBURN": { es: "Radburn", zh: "拉德本", ru: "РАДБЕРН", bn: "র্যাডবার্ন" },
    "RAHWAY": { es: "Rahway", zh: "拉威", ru: "РАУЭЙ", bn: "রাহওয়ে" },
    "RAMSEY": { es: "Ramsey", zh: "拉姆齐", ru: "РАМЗИ", bn: "র্যামসে" },
    "RAMSEY ROUTE 17 STATION": { es: "Estación Ruta 17 Ramsey", zh: "拉姆齐17号公路站", ru: "СТАНЦИЯ РАМЗИ РУТ-17", bn: "র্যামসে রুট ১৭ স্টেশন" },
    "RARITAN": { es: "Raritan", zh: "拉里坦", ru: "РАРИТАН", bn: "রারিটান" },
    "RED BANK": { es: "Banco Rojo", zh: "红岸", ru: "РЕД-БАНК", bn: "রেড ব্যাংক" },
    "RICHARD STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Richard", zh: "理查德街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ РИЧАРД-СТРИТ", bn: "রিচার্ড স্ট্রিট লাইট রেল স্টেশন" },
    "RIDGEWOOD": { es: "Ridgewood", zh: "里奇伍德", ru: "РИДЖВУД", bn: "রিজউড" },
    "RIVER EDGE": { es: "Borde del Río", zh: "河缘", ru: "РИВЕР-ЭДЖ", bn: "রিভার এজ" },
    "RIVERFRONT STADIUM LIGHT RAIL STATION": { es: "Estación Tren Ligero Estadio Riverfront", zh: "河畔体育场轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ СТАДИОН РИВЕРФРОНТ", bn: "রিভারফ্রন্ট স্টেডিয়াম লাইট রেল স্টেশন" },
    "RIVERSIDE LIGHT RAIL STATION": { es: "Estación Tren Ligero Riverside", zh: "河畔轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ РИВЕРСАЙД", bn: "রিভারসাইড লাইট রেল স্টেশন" },
    "RIVERTON LIGHT RAIL STATION": { es: "Estación Tren Ligero Riverton", zh: "里弗顿轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ РИВЕРТОН", bn: "রিভারটন লাইট রেল স্টেশন" },
    "ROEBLING LIGHT RAIL STATION": { es: "Estación Tren Ligero Roebling", zh: "罗布林轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ РЕБЛИНГ", bn: "রোবলিং লাইট রেল স্টেশন" },
    "ROSELLE PARK": { es: "Parque Roselle", zh: "罗塞尔公园", ru: "РОЗЕЛЛ-ПАРК", bn: "রোসেল পার্ক" },
    "ROUTE 73/PENNSAUKEN LIGHT RAIL STATION": { es: "Estación Tren Ligero Ruta 73/Pennsauken", zh: "73号公路/彭索肯轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ РУТ-73/ПЕННСОКЕН", bn: "রুট ৭৩/পেনসাউকেন লাইট রেল স্টেশন" },
    "RUTHERFORD": { es: "Rutherford", zh: "拉瑟福德", ru: "РАЗЕРФОРД", bn: "রাদারফোর্ড" },
    "SALISBURY MILLS-CORNWALL": { es: "Salisbury Mills-Cornwall", zh: "索尔兹伯里米尔斯-康沃尔", ru: "СОЛСБЕРИ-МИЛЛС-КОРНУОЛЛ", bn: "স্যালিসবারি মিলস-কর্নওয়াল" },
    "SECAUCUS LOWER LEVEL": { es: "Secaucus Nivel Inferior", zh: "锡考克斯下层", ru: "СЕКОКУС НИЖНИЙ УРОВЕНЬ", bn: "সেকুকাস লোয়ার লেভেল" },
    "SECAUCUS UPPER LEVEL": { es: "Secaucus Nivel Superior", zh: "锡考克斯上层", ru: "СЕКОКУС ВЕРХНИЙ УРОВЕНЬ", bn: "সেকুকাস আপার লেভেল" },
    "SHORT HILLS": { es: "Colinas Cortas", zh: "短山", ru: "ШОРТ-ХИЛЛС", bn: "শর্ট হিলস" },
    "SILVER LAKE LIGHT RAIL STATION": { es: "Estación Tren Ligero Lago Silver", zh: "银湖轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ СИЛВЕР-ЛЕЙК", bn: "সিলভার লেক লাইট রেল স্টেশন" },
    "SLOATSBURG": { es: "Sloatsburg", zh: "斯洛茨堡", ru: "СЛОУТСБЕРГ", bn: "স্লোটসবার্গ" },
    "SOMERVILLE": { es: "Somerville", zh: "萨默维尔", ru: "СОМЕРВИЛЛ", bn: "সোমারভিল" },
    "SOUTH AMBOY": { es: "Amboy Sur", zh: "南安博伊", ru: "САУТ-АМБОЙ", bn: "সাউথ অ্যামবয়" },
    "SOUTH ORANGE": { es: "Orange Sur", zh: "南奥兰治", ru: "САУТ-ОРАНДЖ", bn: "সাউথ অরেঞ্জ" },
    "SPRING LAKE": { es: "Lago Primavera", zh: "春湖", ru: "СПРИНГ-ЛЕЙК", bn: "স্প্রিং লেক" },
    "SPRING VALLEY": { es: "Valle Primavera", zh: "春谷", ru: "СПРИНГ-ВЕЛЛИ", bn: "স্প্রিং ভ্যালি" },
    "STIRLING": { es: "Stirling", zh: "斯特林", ru: "СТЕРЛИНГ", bn: "স্টার্লিং" },
    "SUFFERN": { es: "Suffern", zh: "萨弗恩", ru: "САФФЕРН", bn: "সাফার্ন" },
    "SUMMIT": { es: "Cumbre", zh: "峰会", ru: "САММИТ", bn: "সামিট" },
    "TETERBORO": { es: "Teterboro", zh: "泰特波罗", ru: "ТЕТЕРБОРО", bn: "টেটারবোরো" },
    "TONNELLE - WESTSIDE DEKALB JCT": { es: "Tonelle - Empalme Westside DeKalb", zh: "托内尔-西侧德卡尔布枢纽", ru: "ТОННЕЛЛ-УЭСТСАЙД-ДЕКАЛЬБ-ДЖАНКШН", bn: "টোনেল-ওয়েস্টসাইড ডেকালব জংশন" },
    "TONNELLE AVENUE LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. Tonnelle", zh: "托内尔大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ТОННЕЛЛ-АВЕНЮ", bn: "টোনেল অ্যাভিনিউ লাইট রেল স্টেশন" },
    "TOWACO": { es: "Towaco", zh: "托瓦科", ru: "ТОВАКО", bn: "টোয়াকো" },
    "TRENTON TRANSIT CENTER": { es: "Centro de Tránsito Trenton", zh: "特伦顿交通中心", ru: "ТРАНЗИТНЫЙ ЦЕНТР ТРЕНТОНА", bn: "ট্রেন্টন ট্রানজিট সেন্টার" },
    "TRENTON TRANSIT CENTER LIGHT RAIL STATION": { es: "Estación Tren Ligero Centro de Tránsito Trenton", zh: "特伦顿交通中心轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ТРАНЗИТНЫЙ ЦЕНТР ТРЕНТОНА", bn: "ট্রেন্টন ট্রানজিট সেন্টার লাইট রেল স্টেশন" },
    "TUXEDO": { es: "Tuxedo", zh: "塔克西多", ru: "ТАКСЕДО", bn: "টাক্সেডো" },
    "UNION": { es: "Union", zh: "联合镇", ru: "ЮНИОН", bn: "ইউনিয়ন" },
    "UPPER MONTCLAIR": { es: "Montclair Superior", zh: "上蒙克莱尔", ru: "АППЕР-МОНТКЛЕР", bn: "আপার মন্টক্লেয়ার" },
    "WALDWICK": { es: "Waldwick", zh: "沃尔德维克", ru: "УОЛДВИК", bn: "ওয়াল্ডউইক" },
    "WALNUT STREET": { es: "Calle Nogal", zh: "核桃街", ru: "УОЛНАТ-СТРИТ", bn: "ওয়ালনাট স্ট্রিট" },
    "WALTER RAND TRANSPORTATION CTR": { es: "Centro de Transporte Walter Rand", zh: "沃尔特·兰德交通中心", ru: "ТРАНСПОРТНЫЙ ЦЕНТР УОЛТЕРА РЭНДА", bn: "ওয়াল্টার র্যান্ড ট্রান্সপোর্টেশন সেন্টার" },
    "WARREN STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Warren", zh: "沃伦街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ УОРРЕН-СТРИТ", bn: "ওয়ারেন স্ট্রিট লাইট রেল স্টেশন" },
    "WASHINGTON STREET LIGHT RAIL STATION": { es: "Estación Tren Ligero Calle Washington", zh: "华盛顿街轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ВАШИНГТОН-СТРИТ", bn: "ওয়াশিংটন স্ট্রিট লাইট রেল স্টেশন" },
    "WATCHUNG AVENUE": { es: "Av. Watchung", zh: "沃楚格大道", ru: "УОТЧУНГ-АВЕНЮ", bn: "ওয়াচুং অ্যাভিনিউ" },
    "WATSESSING AVENUE": { es: "Av. Watsessing", zh: "沃特塞辛大道", ru: "УОТСЕССИНГ-АВЕНЮ", bn: "ওয়াটসেসিং অ্যাভিনিউ" },
    "WAYNE/ROUTE 23 TRANSIT CENTER [RR]": { es: "Centro de Tránsito Wayne/Ruta 23", zh: "韦恩/23号公路交通中心", ru: "ТРАНЗИТНЫЙ ЦЕНТР УЭЙН/РУТ-23", bn: "ওয়েইন/রুট ২৩ ট্রানজিট সেন্টার" },
    "WESMONT": { es: "Wesmont", zh: "韦斯蒙特", ru: "УЭСМОНТ", bn: "ওয়েসমন্ট" },
    "WEST SIDE AVENUE LIGHT RAIL STATION": { es: "Estación Tren Ligero Av. West Side", zh: "西侧大道轻轨站", ru: "СТАНЦИЯ ЛАЙТ-РЕЙЛ ВЕСТ-САЙД-АВЕНЮ", bn: "ওয়েস্ট সাইড অ্যাভিনিউ লাইট রেল স্টেশন" },
    "WESTFIELD": { es: "Westfield", zh: "韦斯特菲尔德", ru: "УЭСТФИЛД", bn: "ওয়েস্টফিল্ড" },
    "WESTWOOD": { es: "Westwood", zh: "韦斯特伍德", ru: "УЭСТВУД", bn: "ওয়েস্টউড" },
    "WHITE HOUSE": { es: "Casa Blanca", zh: "白宫", ru: "УАЙТ-ХАУС", bn: "হোয়াইট হাউস" },
    "WOOD-RIDGE": { es: "Wood-Ridge", zh: "伍德里奇", ru: "ВУД-РИДЖ", bn: "উড-রিজ" },
    "WOODBRIDGE": { es: "Woodbridge", zh: "伍德布里奇", ru: "ВУДБРИДЖ", bn: "উডব্রিজ" },
    "WOODCLIFF LAKE": { es: "Lago Woodcliff", zh: "伍德克利夫湖", ru: "ВУДКЛИФФ-ЛЕЙК", bn: "উডক্লিফ লেক" }
};
